-- =======================================================
-- SCRIPT SQL PARA CRIAÇÃO DAS TABELAS NO ORACLE
-- Aplicação: DRG-GUIAS (FastAPI)
-- Usuário: inovemed
-- Tablespace: MV2000_D
-- =======================================================

-- =======================================================
-- 1. TABELA PRINCIPAL: INOVEMED_TBL_GUIAS
-- =======================================================
CREATE TABLE inovemed_tbl_guias (
    -- Campos principais
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_guia VARCHAR2(20 CHAR) NOT NULL,
    codigo_operadora VARCHAR2(6 CHAR) NOT NULL,
    numero_guia_operadora VARCHAR2(20 CHAR),
    numero_guia_internacao VARCHAR2(20 CHAR),
    data_autorizacao DATE NOT NULL,
    senha VARCHAR2(20 CHAR),
    data_validade DATE,
    
    -- Dados do beneficiário
    numero_carteira VARCHAR2(20 CHAR) NOT NULL,
    data_validade_carteira DATE,
    rn VARCHAR2(1 CHAR), -- S/N
    data_nascimento DATE NOT NULL,
    sexo VARCHAR2(1 CHAR) NOT NULL, -- M/F/I
    situacao_beneficiario VARCHAR2(1 CHAR) NOT NULL, -- A/I
    nome_beneficiario VARCHAR2(100 CHAR) NOT NULL,
    
    -- Dados do prestador
    codigo_prestador VARCHAR2(14 CHAR) NOT NULL,
    nome_prestador VARCHAR2(70 CHAR) NOT NULL,
    nome_profissional VARCHAR2(70 CHAR),
    codigo_profissional VARCHAR2(2 CHAR) NOT NULL,
    numero_registro_profissional VARCHAR2(15 CHAR) NOT NULL,
    uf_profissional VARCHAR2(2 CHAR) NOT NULL,
    codigo_cbo VARCHAR2(6 CHAR) NOT NULL,
    
    -- Dados do hospital
    codigo_contratado VARCHAR2(14 CHAR) NOT NULL,
    nome_hospital VARCHAR2(70 CHAR) NOT NULL,
    porte_hospital VARCHAR2(1 CHAR) , -- 1-4
    complexidade_hospital VARCHAR2(1 CHAR), -- 1-3
    esfera_administrativa VARCHAR2(1 CHAR) , -- 1-3
    endereco_hospital CLOB DEFAULT 'Endereço não informado',
    data_sugerida_internacao DATE NOT NULL,
    carater_atendimento VARCHAR2(1 CHAR) NOT NULL, -- 1-5
    tipo_internacao VARCHAR2(1 CHAR) NOT NULL, -- 1-5
    regime_internacao VARCHAR2(1 CHAR) NOT NULL, -- 1-5
    diarias_solicitadas NUMBER NOT NULL,
    previsao_uso_opme VARCHAR2(1 CHAR), -- S/N
    previsao_uso_quimioterapico VARCHAR2(1 CHAR), -- S/N
    indicacao_clinica CLOB NOT NULL,
    indicacao_acidente VARCHAR2(1 CHAR) NOT NULL, -- 0-2
    tipo_acomodacao_solicitada VARCHAR2(2 CHAR), -- 1-2
    
    -- Dados da autorização
    data_admissao_estimada DATE,
    qtde_diarias_autorizadas NUMBER,
    tipo_acomodacao_autorizada VARCHAR2(2 CHAR),
    cnes_autorizado VARCHAR2(7 CHAR),
    observacao_guia CLOB,
    data_solicitacao DATE NOT NULL,
    justificativa_operadora CLOB,
    
    -- Dados complementares
    natureza_guia VARCHAR2(1 CHAR) NOT NULL, -- 1-6
    guia_complementar VARCHAR2(1 CHAR) NOT NULL, -- S/N
    situacao_guia VARCHAR2(2 CHAR) NOT NULL, -- A/P/N/C/S
    tipo_doenca VARCHAR2(1 CHAR), -- 1-2
    tempo_doenca NUMBER,
    longa_permanencia VARCHAR2(1 CHAR), -- 1-2
    motivo_encerramento VARCHAR2(2 CHAR), -- 1-5,9
    tipo_alta VARCHAR2(2 CHAR), -- 1-8
    data_alta DATE,
    
    -- Campos de controle
    data_criacao DATE DEFAULT SYSDATE,
    data_atualizacao DATE DEFAULT SYSDATE,
    tp_status VARCHAR2(1 CHAR) NOT NULL DEFAULT 'A', -- A/T/E
    data_processamento DATE,
    mensagem_erro CLOB,
    tentativas NUMBER DEFAULT 0
) TABLESPACE MV2000_D;

-- Índices para tabela principal
CREATE UNIQUE INDEX idx_inovemed_guias_numero ON inovemed_tbl_guias(numero_guia) TABLESPACE MV2000_D;
CREATE INDEX idx_inovemed_guias_carteira ON inovemed_tbl_guias(numero_carteira) TABLESPACE MV2000_D;
CREATE INDEX idx_inovemed_guias_status ON inovemed_tbl_guias(tp_status) TABLESPACE MV2000_D;
CREATE INDEX idx_inovemed_guias_data_criacao ON inovemed_tbl_guias(data_criacao) TABLESPACE MV2000_D;

-- =======================================================
-- 2. TABELA: INOVEMED_TBL_DIAGNOSTICOS
-- =======================================================
CREATE TABLE inovemed_tbl_diagnosticos (
    -- Campos principais
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(4 CHAR) NOT NULL, -- CID-10
    tipo VARCHAR2(1 CHAR) NOT NULL, -- P/S
    
    -- Chave estrangeira
    guia_id NUMBER NOT NULL,
    
    -- Constraints
    CONSTRAINT fk_diagnosticos_guia FOREIGN KEY (guia_id) 
        REFERENCES inovemed_tbl_guias(id) ON DELETE CASCADE
) TABLESPACE MV2000_D;

-- Índices para diagnósticos
CREATE INDEX idx_diagnosticos_guia ON inovemed_tbl_diagnosticos(guia_id) TABLESPACE MV2000_D;
CREATE INDEX idx_diagnosticos_codigo ON inovemed_tbl_diagnosticos(codigo) TABLESPACE MV2000_D;

-- =======================================================
-- 3. TABELA: INOVEMED_TBL_PROCEDIMENTOS
-- =======================================================
CREATE TABLE inovemed_tbl_procedimentos (
    -- Campos principais
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela VARCHAR2(2 CHAR) NOT NULL, -- 00, 20, 22, 98
    codigo VARCHAR2(10 CHAR) NOT NULL,
    descricao VARCHAR2(150 CHAR) NOT NULL,
    qtde_solicitada NUMBER NOT NULL,
    valor_unitario NUMBER(8,2) NOT NULL,
    qtde_autorizada NUMBER NOT NULL,
    
    -- Chave estrangeira
    guia_id NUMBER NOT NULL,
    
    -- Constraints
    CONSTRAINT fk_procedimentos_guia FOREIGN KEY (guia_id) 
        REFERENCES inovemed_tbl_guias(id) ON DELETE CASCADE
) TABLESPACE MV2000_D;

-- Índices para procedimentos
CREATE INDEX idx_procedimentos_guia ON inovemed_tbl_procedimentos(guia_id) TABLESPACE MV2000_D;
CREATE INDEX idx_procedimentos_codigo ON inovemed_tbl_procedimentos(codigo) TABLESPACE MV2000_D;

-- =======================================================
-- 4. TABELA: INOVEMED_TBL_ANEXOS
-- =======================================================
CREATE TABLE inovemed_tbl_anexos (
    -- Campos principais
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_lote_documento VARCHAR2(12 CHAR),
    numero_protocolo_documento VARCHAR2(12 CHAR),
    formato_documento VARCHAR2(2 CHAR) NOT NULL, -- 1-5, 99
    sequencial_documento NUMBER,
    data_criacao DATE NOT NULL,
    nome VARCHAR2(500 CHAR) NOT NULL,
    url_documento VARCHAR2(500 CHAR) NOT NULL,
    observacao_documento VARCHAR2(500 CHAR),
    tipo_documento VARCHAR2(2 CHAR) NOT NULL, -- 01-04, 99
    
    -- Chave estrangeira
    guia_id NUMBER NOT NULL,
    
    -- Constraints
    CONSTRAINT fk_anexos_guia FOREIGN KEY (guia_id) 
        REFERENCES inovemed_tbl_guias(id) ON DELETE CASCADE
) TABLESPACE MV2000_D;

-- Índices para anexos
CREATE INDEX idx_anexos_guia ON inovemed_tbl_anexos(guia_id) TABLESPACE MV2000_D;
CREATE INDEX idx_anexos_tipo ON inovemed_tbl_anexos(tipo_documento) TABLESPACE MV2000_D;

-- =======================================================
-- 5. TRIGGER PARA ATUALIZAR DATA_ATUALIZACAO
-- =======================================================
CREATE OR REPLACE TRIGGER tr_inovemed_guias_update
    BEFORE UPDATE ON inovemed_tbl_guias
    FOR EACH ROW
BEGIN
    :NEW.data_atualizacao := SYSDATE;
END;
/

-- =======================================================
-- 6. COMENTÁRIOS DAS TABELAS
-- =======================================================
COMMENT ON TABLE inovemed_tbl_guias IS 'Tabela principal para guias de internação';
COMMENT ON TABLE inovemed_tbl_diagnosticos IS 'Diagnósticos associados às guias (CID-10)';
COMMENT ON TABLE inovemed_tbl_procedimentos IS 'Procedimentos associados às guias';
COMMENT ON TABLE inovemed_tbl_anexos IS 'Anexos/documentos associados às guias';

-- =======================================================
-- 7. PERMISSÕES PARA O USUÁRIO INOVEMED
-- =======================================================
-- Executar como DBA:
-- GRANT SELECT, INSERT, UPDATE, DELETE ON inovemed_tbl_guias TO inovemed;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON inovemed_tbl_diagnosticos TO inovemed;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON inovemed_tbl_procedimentos TO inovemed;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON inovemed_tbl_anexos TO inovemed;

-- =======================================================
-- 8. SEQUENCES (para compatibilidade com autoincrement)
-- =======================================================
-- As sequences são criadas automaticamente pelo Oracle 12c+
-- com a cláusula GENERATED BY DEFAULT AS IDENTITY

-- =======================================================
-- SCRIPT CONCLUÍDO
-- =======================================================
-- 
-- INSTRUÇÕES PARA O DBA:
-- 
-- 1. Executar este script como usuário com privilégios DBA
-- 2. Garantir que o usuário 'inovemed' tenha quota no tablespace 'MV2000_D'
-- 3. Executar os GRANTs comentados no final do script
-- 4. Verificar se as tabelas foram criadas corretamente
--
-- COMANDOS DE VERIFICAÇÃO:
-- SELECT table_name FROM user_tables WHERE table_name LIKE 'INOVEMED_%';
-- SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'ISEQ$$_%';
--
-- =======================================================
