-- ========================================
-- DADOS DE TESTE PARA SISTEMA DRG FASTAPI
-- 5 Guias com status "A" (Aguardando processamento)
-- ========================================

-- Guia 1: Paciente com dor abdominal
INSERT INTO inovemed_tbl_guias (
    numero_guia,
    codigo_operadora,
    numero_guia_operadora,
    numero_guia_internacao,
    data_autorizacao,
    senha,
    data_validade,
    numero_carteira,
    data_validade_carteira,
    rn,
    data_nascimento,
    sexo,
    situacao_beneficiario,
    codigo_prestador,
    nome_prestador,
    nome_profissional,
    codigo_profissional,
    numero_registro_profissional,
    uf_profissional,
    codigo_cbo,
    codigo_contratado,
    nome_hospital,
    data_sugerida_internacao,
    carater_atendimento,
    tipo_internacao,
    regime_internacao,
    diarias_solicitadas,
    previsao_uso_opme,
    previsao_uso_quimioterapico,
    indicacao_clinica,
    indicacao_acidente,
    tipo_acomodacao_solicitada,
    data_admissao_estimada,
    qtde_diarias_autorizadas,
    tipo_acomodacao_autorizada,
    cnes_autorizado,
    observacao_guia,
    data_solicitacao,
    justificativa_operadora,
    natureza_guia,
    guia_complementar,
    situacao_guia,
    tipo_doenca,
    tempo_doenca,
    longa_permanencia,
    tp_status,
    tentativas
) VALUES (
    'GUI001234567',
    '123456',
    'OP001234567',
    'INT001234567',
    '2024-01-15',
    'SENHA001',
    '2024-02-15',
    'CART001234567',
    '2025-12-31',
    'N',
    '1985-03-15 00:00:00',
    'M',
    'A',
    '12345678901234',
    'HOSPITAL SÃO PAULO LTDA',
    'DR. JOAO SILVA',
    '01',
    'CRM123456',
    'SP',
    '123456',
    '98765432109876',
    'HOSPITAL SÃO PAULO LTDA',
    '2024-01-16',
    '1',
    '1',
    '1',
    5,
    'N',
    'N',
    'Paciente com quadro de dor abdominal aguda, necessitando investigação e possível intervenção cirúrgica.',
    '0',
    '01',
    '2024-01-16',
    5,
    '01',
    '1234567',
    'Autorização para internação hospitalar',
    '2024-01-15',
    'Autorizado conforme protocolo médico',
    '1',
    'N',
    'A',
    '1',
    30,
    '1',
    'A',
    0
);

-- Guia 2: Paciente com infecção respiratória
INSERT INTO inovemed_tbl_guias (
    numero_guia,
    codigo_operadora,
    numero_guia_operadora,
    numero_guia_internacao,
    data_autorizacao,
    senha,
    data_validade,
    numero_carteira,
    data_validade_carteira,
    rn,
    data_nascimento,
    sexo,
    situacao_beneficiario,
    codigo_prestador,
    nome_prestador,
    nome_profissional,
    codigo_profissional,
    numero_registro_profissional,
    uf_profissional,
    codigo_cbo,
    codigo_contratado,
    nome_hospital,
    data_sugerida_internacao,
    carater_atendimento,
    tipo_internacao,
    regime_internacao,
    diarias_solicitadas,
    previsao_uso_opme,
    previsao_uso_quimioterapico,
    indicacao_clinica,
    indicacao_acidente,
    tipo_acomodacao_solicitada,
    data_admissao_estimada,
    qtde_diarias_autorizadas,
    tipo_acomodacao_autorizada,
    cnes_autorizado,
    observacao_guia,
    data_solicitacao,
    justificativa_operadora,
    natureza_guia,
    guia_complementar,
    situacao_guia,
    tipo_doenca,
    tempo_doenca,
    longa_permanencia,
    tp_status,
    tentativas
) VALUES (
    'GUI002345678',
    '234567',
    'OP002345678',
    'INT002345678',
    '2024-01-16',
    'SENHA002',
    '2024-02-16',
    'CART002345678',
    '2025-12-31',
    'N',
    '1990-07-20 00:00:00',
    'F',
    'A',
    '23456789012345',
    'CLINICA MÉDICA LTDA',
    'DRA. MARIA SANTOS',
    '02',
    'CRM234567',
    'RJ',
    '234567',
    '87654321098765',
    'CLINICA MÉDICA LTDA',
    '2024-01-17',
    '2',
    '2',
    '2',
    3,
    'N',
    'N',
    'Paciente com quadro de infecção respiratória, necessitando tratamento hospitalar.',
    '0',
    '01',
    '2024-01-17',
    3,
    '01',
    '2345678',
    'Autorização para internação clínica',
    '2024-01-16',
    'Autorizado conforme protocolo médico',
    '2',
    'S',
    'A',
    '1',
    15,
    '1',
    'A',
    0
);

-- Guia 3: Paciente com fratura
INSERT INTO inovemed_tbl_guias (
    numero_guia,
    codigo_operadora,
    numero_guia_operadora,
    numero_guia_internacao,
    data_autorizacao,
    senha,
    data_validade,
    numero_carteira,
    data_validade_carteira,
    rn,
    data_nascimento,
    sexo,
    situacao_beneficiario,
    codigo_prestador,
    nome_prestador,
    nome_profissional,
    codigo_profissional,
    numero_registro_profissional,
    uf_profissional,
    codigo_cbo,
    codigo_contratado,
    nome_hospital,
    data_sugerida_internacao,
    carater_atendimento,
    tipo_internacao,
    regime_internacao,
    diarias_solicitadas,
    previsao_uso_opme,
    previsao_uso_quimioterapico,
    indicacao_clinica,
    indicacao_acidente,
    tipo_acomodacao_solicitada,
    data_admissao_estimada,
    qtde_diarias_autorizadas,
    tipo_acomodacao_autorizada,
    cnes_autorizado,
    observacao_guia,
    data_solicitacao,
    justificativa_operadora,
    natureza_guia,
    guia_complementar,
    situacao_guia,
    tipo_doenca,
    tempo_doenca,
    longa_permanencia,
    tp_status,
    tentativas
) VALUES (
    'GUI003456789',
    '345678',
    'OP003456789',
    'INT003456789',
    '2024-01-17',
    'SENHA003',
    '2024-02-17',
    'CART003456789',
    '2025-12-31',
    'N',
    '1975-11-10 00:00:00',
    'M',
    'A',
    '34567890123456',
    'HOSPITAL ORTOPÉDICO LTDA',
    'DR. CARLOS OLIVEIRA',
    '03',
    'CRM345678',
    'MG',
    '345678',
    '76543210987654',
    'HOSPITAL ORTOPÉDICO LTDA',
    '2024-01-18',
    '3',
    '3',
    '3',
    7,
    'S',
    'N',
    'Paciente com fratura de fêmur, necessitando cirurgia ortopédica.',
    '1',
    '02',
    '2024-01-18',
    7,
    '02',
    '3456789',
    'Autorização para cirurgia ortopédica',
    '2024-01-17',
    'Autorizado conforme protocolo médico',
    '3',
    'N',
    'A',
    '2',
    1,
    '2',
    'A',
    0
);

-- Guia 4: Paciente com problema cardíaco
INSERT INTO inovemed_tbl_guias (
    numero_guia,
    codigo_operadora,
    numero_guia_operadora,
    numero_guia_internacao,
    data_autorizacao,
    senha,
    data_validade,
    numero_carteira,
    data_validade_carteira,
    rn,
    data_nascimento,
    sexo,
    situacao_beneficiario,
    codigo_prestador,
    nome_prestador,
    nome_profissional,
    codigo_profissional,
    numero_registro_profissional,
    uf_profissional,
    codigo_cbo,
    codigo_contratado,
    nome_hospital,
    data_sugerida_internacao,
    carater_atendimento,
    tipo_internacao,
    regime_internacao,
    diarias_solicitadas,
    previsao_uso_opme,
    previsao_uso_quimioterapico,
    indicacao_clinica,
    indicacao_acidente,
    tipo_acomodacao_solicitada,
    data_admissao_estimada,
    qtde_diarias_autorizadas,
    tipo_acomodacao_autorizada,
    cnes_autorizado,
    observacao_guia,
    data_solicitacao,
    justificativa_operadora,
    natureza_guia,
    guia_complementar,
    situacao_guia,
    tipo_doenca,
    tempo_doenca,
    longa_permanencia,
    tp_status,
    tentativas
) VALUES (
    'GUI004567890',
    '456789',
    'OP004567890',
    'INT004567890',
    '2024-01-18',
    'SENHA004',
    '2024-02-18',
    'CART004567890',
    '2025-12-31',
    'N',
    '1960-05-25 00:00:00',
    'F',
    'A',
    '45678901234567',
    'HOSPITAL CARDÍACO LTDA',
    'DRA. ANA COSTA',
    '04',
    'CRM456789',
    'RS',
    '456789',
    '65432109876543',
    'HOSPITAL CARDÍACO LTDA',
    '2024-01-19',
    '4',
    '4',
    '4',
    10,
    'N',
    'N',
    'Paciente com quadro de insuficiência cardíaca, necessitando monitoramento intensivo.',
    '0',
    '01',
    '2024-01-19',
    10,
    '01',
    '4567890',
    'Autorização para internação cardiológica',
    '2024-01-18',
    'Autorizado conforme protocolo médico',
    '4',
    'S',
    'A',
    '1',
    90,
    '2',
    'A',
    0
);

-- Guia 5: Paciente com problema neurológico
INSERT INTO inovemed_tbl_guias (
    numero_guia,
    codigo_operadora,
    numero_guia_operadora,
    numero_guia_internacao,
    data_autorizacao,
    senha,
    data_validade,
    numero_carteira,
    data_validade_carteira,
    rn,
    data_nascimento,
    sexo,
    situacao_beneficiario,
    codigo_prestador,
    nome_prestador,
    nome_profissional,
    codigo_profissional,
    numero_registro_profissional,
    uf_profissional,
    codigo_cbo,
    codigo_contratado,
    nome_hospital,
    data_sugerida_internacao,
    carater_atendimento,
    tipo_internacao,
    regime_internacao,
    diarias_solicitadas,
    previsao_uso_opme,
    previsao_uso_quimioterapico,
    indicacao_clinica,
    indicacao_acidente,
    tipo_acomodacao_solicitada,
    data_admissao_estimada,
    qtde_diarias_autorizadas,
    tipo_acomodacao_autorizada,
    cnes_autorizado,
    observacao_guia,
    data_solicitacao,
    justificativa_operadora,
    natureza_guia,
    guia_complementar,
    situacao_guia,
    tipo_doenca,
    tempo_doenca,
    longa_permanencia,
    tp_status,
    tentativas
) VALUES (
    'GUI005678901',
    '567890',
    'OP005678901',
    'INT005678901',
    '2024-01-19',
    'SENHA005',
    '2024-02-19',
    'CART005678901',
    '2025-12-31',
    'N',
    '1982-12-08 00:00:00',
    'M',
    'A',
    '56789012345678',
    'HOSPITAL NEUROLÓGICO LTDA',
    'DR. PEDRO FERREIRA',
    '05',
    'CRM567890',
    'PR',
    '567890',
    '54321098765432',
    'HOSPITAL NEUROLÓGICO LTDA',
    '2024-01-20',
    '5',
    '5',
    '5',
    8,
    'S',
    'S',
    'Paciente com quadro de cefaleia intensa e alterações neurológicas, necessitando investigação especializada.',
    '0',
    '01',
    '2024-01-20',
    8,
    '01',
    '5678901',
    'Autorização para internação neurológica',
    '2024-01-19',
    'Autorizado conforme protocolo médico',
    '5',
    'N',
    'A',
    '1',
    45,
    '1',
    'A',
    0
);

-- ========================================
-- FIM DOS DADOS DE TESTE
-- Total: 5 guias com status "A" (Aguardando processamento)
-- ========================================
